### PR TITLE
Copy from kubernetes/website tags/release-1.10

### PR DESCRIPTION
**Pull request by nasa9084**
This is initial commit to translate into Japanese.
I copied files from tags/release-1.10 on kubernetes/website repository, except files existing on this repository.

### CODE REVIEW

**Comment by cstoku** [comment]
@zacharysarah Should we include `content/cn` when importing `release-1.10` into this repository?

**Comment by zacharysarah** [comment]
@cstoku No, just `content/en/`. :+1:

**Comment by cstoku** [comment]
@zacharysarah Thanks!!
@nasa9084 というわけで `content/cn` を削除するコミットを追加してもらえますか？それが行けたらMergeしましょう！

**Comment by nasa9084** [comment]
I removed `content/cn` directory!

**Pull request merged**
