### PR TITLE
Relocate some yaml files to the proper directory (1.10)

### LINKED ISSUE #22: Hogo server does not work / Deploy preview failed
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
`hugo server --navigateToChanged` does not work. 

**Proposed Solution:**
I think that some file is missing.
It is necessary to confirm what is missing.

**Page to Update:**
https://kubernetes.io/...

### PR DESCRIPTION
**Pull request by tnir**
This PR makes `hugo` work well in CI process and translator's local environment.

See the original PR https://github.com/kubernetes/website/pull/10219, the origin of the bug kubernetes/website#8635, the original issue to fix this kubernetes/website#10218

Closes #22

### CODE REVIEW

**Comment by tnir** [comment]
@zembutsu I would prefer this rather than #24 due to no changes in `content/ja/` in this change.

**Comment by tnir** [comment]
@cstoku @nasa9084 Could you review this as reviewing PRs in markdown format is too hard to get it  merged... (e.g., #8)?

**Comment by tnir** [comment]
We can now confirm `hugo` works well 😄 with Review Apps work: https://5b9787d9b312746769a92d61--kubernetes-docs-ja.netlify.com/

**Comment by nasa9084** [comment]
動かなかったのが動くようになっているならOKかと思います！
/lgtm

**Comment by tnir** [comment]
ありがとうございます。

/approve

**Pull request merged**
